project:
  type: book
  output-dir: docs

book:
  title: "Stan and R for Pharmacometrics"
  author:
    - Casey Davis
    - Yasong Lu
    - Arya Pourzanjani
    - Pavan Vaddady
  repo-url: https://github.com/cbdavis33/cbdavis33.github.io
  repo-branch: master
  repo-actions: [issue]
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - part: Curriculum
      chapters: 
        - intro.qmd
        - stancodeblocks.qmd
        - logisticregression.qmd
    - part: Support
      chapters:
        - installation.qmd
        - logreg_ho_solution.qmd
        - summary.qmd
        - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

